version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 5
    target-branch: "renovate_21_1"
    allowed_updates:
    - match:
        update_type: "security"
