version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase-if-necessar
    open-pull-requests-limit: 20
    target-branch: "dependabot_2_21_1"
  
